### ISSUE TITLE
有个光敏电阻怎么读数据

### ISSUE THREAD

**Issue by zhtrx** [happyme531/RoomeSwitchgenieCtrl#3]
有个光敏电阻怎么读数据

**Comment by happyme531** [comment]
暂时没做，等我几天2022年1月6日 下午7:16，zhtrx ***@***.***>写道：

有个光敏电阻怎么读数据

**Comment by happyme531** [comment]
这个光敏电阻是为了实现光感自动开/关灯而设计的，似乎没发现有什么途径可以读取光照数据...
